name: book-keeper-prod

services:
    app:
        container_name: taqsimot-app-prod
        image: '${BOOK_KEEPER_PROD_IMAGE:-book-keeper-prod-app}:latest'
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        env_file:
            - .env.production
        volumes:
            - prod-storage:/var/www/html/storage
            - prod-database:/var/www/html/database
        networks:
            - prod
            - traefik-net

    queue:
        image: '${BOOK_KEEPER_PROD_IMAGE:-book-keeper-prod-app}:latest'
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        command: php artisan queue:work --verbose --tries=3 --timeout=600
        depends_on:
            - app
        env_file:
            - .env.production
        volumes:
            - prod-storage:/var/www/html/storage
            - prod-database:/var/www/html/database
        networks:
            - prod

volumes:
    prod-storage:
    prod-database:

networks:
    prod:
        driver: bridge
    traefik-net:
        external: true
