[program:book-keeper-scheduler]
process_name=%(program_name)s
command=php /home/akmal/Projects/book-keeper/artisan schedule:work
autostart=true
autorestart=true
user=akmal
redirect_stderr=true
stdout_logfile=/home/akmal/Projects/book-keeper/storage/logs/scheduler.log
