[program:book-keeper-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/akmal/Projects/book-keeper/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=akmal
numprocs=2
redirect_stderr=true
stdout_logfile=/home/akmal/Projects/book-keeper/storage/logs/worker.log
stopwaitsecs=3600
